"""
This type stub file was generated by pyright.
"""

class BaseDocumenter(object):
    def __init__(self, resource) -> None:
        ...
    
    @property
    def class_name(self):
        ...
    


