"""
This type stub file was generated by pyright.
"""

def get_resource_ignore_params(params):
    """Helper method to determine which parameters to ignore for actions

    :returns: A list of the parameter names that does not need to be
        included in a resource's method call for documentation purposes.
    """
    ...

def is_resource_action(action_handle):
    ...

def get_resource_public_actions(resource_class):
    ...

def get_identifier_values_for_example(identifier_names):
    ...

def get_identifier_args_for_signature(identifier_names):
    ...

def get_identifier_description(resource_name, identifier_name):
    ...

def add_resource_type_overview(section, resource_type, description, intro_link=...):
    ...

class DocumentModifiedShape(object):
    def __init__(self, shape_name, new_type, new_description, new_example_value) -> None:
        ...
    
    def replace_documentation_for_matching_shape(self, event_name, section, **kwargs):
        ...
    


