"""
This type stub file was generated by pyright.
"""

import sys
import os
import socket
from botocore.vendored import six

if six.PY3:
    SOCKET_ERROR = ConnectionError
else:
    SOCKET_ERROR = socket.error
if six.PY3:
    ...
else:
    ...
if sys.platform.startswith('win'):
    def rename_file(current_filename, new_filename):
        ...
    
else:
    rename_file = os.rename
